### ISSUE TITLE
Links in README need fixing

### ISSUE THREAD

**Issue by koeaw** [acdh-oeaw/apis-rdf-devops#1]
**Describe the bug**
The links to the **apis-ontologies** submodule in [the README](https://github.com/acdh-oeaw/apis-rdf-devops#symlink-relevant-apis-ontologies-files) need updating.

**To Reproduce**
1. Go to "[Symlink relevant APIS Ontologies files](https://github.com/acdh-oeaw/apis-rdf-devops#symlink-relevant-apis-ontologies-files)" in this project's `README.md` file
2. Click on any of the three links included in the section
3. See 404 Not Found error + redirect to [gitlab.com](https://gitlab.com/)

**Expected behavior**
The links should point to (files contained within) the [apis-ontologies](https://github.com/acdh-oeaw/apis-ontologies) repository on GitHub. 

**Additional context**
Link breakage is due to GitLab and GitHub resolving relative links between repositories differently. The links should probably get updated to absolute URLs since the repositories on github.com are our official code sources now.

**Comment by yashkathe** [comment]
I can take up this issue.
Can you just paste the links to the files which need to be included in the readme.

**Comment by koeaw** [comment]
@yashkathe Thanks for the offer! We only just moved our code to GitHub and are still ironing out the details of (external) collaborations. Until then, it'd be best to hold off; I hope to be able to get back to you within the next 1-2 weeks.

**Comment by yashkathe** [comment]
Okay let me know thanks.

**Comment by koeaw** [comment]
This got fixed a while ago (I believe by myself while updating other contents of the README).

@yashkathe Sorry, we still haven't got around to adding files for laying down some ground rules for working with outside collaborators so couldn't assign this task to someone else.
