### ISSUE TITLE
Delete apis_core softlink

### ISSUE THREAD

**Issue by b1rger** [acdh-oeaw/apis-rdf-devops#25]
The `apis_core` softlink is possibly not needed anywhere, we could therefore
delete it to reduce complexity of the devops setup.

**Comment by koeaw** [comment]
@b1rger Only tangentially related, but the triage label is only for temporary use, it's basically meant to communicate a ticket hasn't been properly categorised yet by devs (relevant for when tickets are opened by collaborators or third parties).

**Comment by b1rger** [comment]
> @b1rger Only tangentially related, but the triage label is only for temporary use, it's basically meant to communicate a ticket hasn't been properly categorised yet by devs (relevant for when tickets are opened by collaborators or third parties).

Ah, thanks for this insight! Apparently it get automatically assigned if i choose the bug report template. I'll try to avoid that ;)

**Comment by koeaw** [comment]
Also, it would be great to add all issues and PRs to the board – if any of them need to be referenced again at a later point it'll be a pain to try to find them again otherwise because of the three-repo structure.

**Comment by koeaw** [comment]
Yeah, it's part of the templates for this exact reason, but, you can remove it while you're opening a new issue and it will never be applied. I.e. you can continue to use the templates just fine!

**Comment by b1rger** [comment]
> Yeah, it's part of the templates for this exact reason, but, you can remove it while you're opening a new issue (just remove it from the sidebar at any point before hitting the Create button) and it will never be applied. I.e. you can continue to use the templates just fine!

I'm not using the webinterface to create issues, but I'll figure something out ;)

**Comment by koeaw** [comment]
> I'm not using the webinterface to create issues, but I'll figure something out ;)

Ohh, I see! The GitHub CLI then? It's possible that GitHub Projects can't be access via the API yet (I seem to remember something about that last time I looked at their docs or public timeline...) /:

**Comment by b1rger** [comment]
This was implement in 45739d3e039ef83e96f88c6d995dc444e21fe592
