### ISSUE TITLE
Django templates cannot be overridden

### ISSUE THREAD

**Issue by koeaw** [acdh-oeaw/apis-rdf-devops#3]
Existing `apis_core` templates cannot currently be overridden.

Reasons:
* missing `TEMPLATES` setting which would allow individual Ontologies apps to replace templates (reporter: @gythaogg)
* incorrect setup of templates and template tags for `webpage` (reporter: @koeaw)

**Comment by koeaw** [comment]
@gythaogg Removing you as assignee since the one part of the solution to this issue was successfully merged.

**Comment by gythaogg** [comment]
Thanks, @koeaw

**Comment by b1rger** [comment]
Just for the record: the commit in bf2b4c7 adds a directory to the template backend, but the directory path is calculated based on where the `base.py` settings file from apis-rdf-core is installed. So in our container setup for example, that is `/usr/local/lib/python3.8/site-packages/apis/base.py` and the path added to the template backend is therefore `/usr/local/lib/python3.8/site-packages/apis_ontoloy/templates` which does not exist.
It is possible though to add a custom template path in the ontologies settings, by using:
```
ONTOLOGY_DIR = os.path.dirname(os.path.dirname(__file__))
for template in TEMPLATES:
  template["DIRS"].append(os.path.join(ONTOLOGY_DIR, "templates"))
```
which will then pick up templates in your ontology folder.

(As usual, there is also the option to decide to make the apis-ontologies to be real Django apps, then the `"APP_DIRS": True,` setting of the template backend would pick up the templates automatically.)

**Comment by steffres** [comment]
Seems like a more stable approach with the path logic run in apis-ontologies. 

And making apis-ontologies itself a Django app for this reason here and likely more sounds reasonable too, we should look further into this.

**Comment by koeaw** [comment]
New issue which may affect this issue / what was discussed in here more recently: https://github.com/acdh-oeaw/apis-rdf-devops/issues/59

**Comment by koeaw** [comment]
> Just for the record: the commit in [bf2b4c7](https://github.com/acdh-oeaw/apis-rdf-devops/commit/bf2b4c719311b9008898414c755882819eb1ef12) adds a directory to the template backend, but (...) the path added to the template backend (...) does not exist.

So that commit should actually be reverted? (Because it's of no use?)

> It is possible though to add a custom template path in the ontologies settings, by using (snip) which will then pick up templates in your ontology folder.

Thanks, @b1rger, I used your example/what you did in SicProd to update `server_settings.py` in the [PR I created to add more files](https://github.com/acdh-oeaw/apis-ontologies/pull/7) to `example_project` (which I've updated/reworked/set to active again).

---

The rest of the comments...

> (As usual, there is also the option to decide to make the apis-ontologies to be real Django apps, then the `"APP_DIRS": True,` setting of the template backend would pick up the templates automatically.)

&

> Seems like a more stable approach with the path logic run in apis-ontologies.
 > And making apis-ontologies itself a Django app for this reason here and likely more sounds reasonable too, we should look further into this.

...  are valid, but go beyond the original scope of this issue, which I'd like to close once further action on commit [bf2b4c7](https://github.com/acdh-oeaw/apis-rdf-devops/commit/bf2b4c719311b9008898414c755882819eb1ef12) is decided on.

**Comment by b1rger** [comment]
this is now possible due to apis-core-rdf being a normal django app
