### ISSUE TITLE
Automate project assignment

### ISSUE THREAD

**Issue by b1rger** [acdh-oeaw/apis-rdf-devops#30]
All issues and pull requests should be added to the shared project. This
workflow can be automated to free resources for more challenging tasks.

**Comment by koeaw** [comment]
@b1rger I just saw that the official (beta) workflow to solve this problem was made available in our project workflows. Unfortunately, it currently only allows picking of one repo, so I decided to enable it for `apis-core-rdf` for now.

**Comment by b1rger** [comment]
> I just saw that the official (beta) workflow to solve this problem was made available in our project workflows. Unfortunately, it currently only allows picking of one repo, so I decided to enable it for `apis-core-rdf` for now.

nice!
