### ISSUE TITLE
Outdated poetry commands in Dockerfile?

### ISSUE THREAD

**Issue by koeaw** [acdh-oeaw/apis-rdf-devops#40]
We're still checking for the existence of a(n undocumented) variable `$INSTALL_DEV` in the Dockerfile to run two variations of the `poetry install` command:

```
RUN bash -c "if [ $INSTALL_DEV == 'true' ] ; then poetry install --no-root ; else poetry install --no-root --no-dev ; fi"
```

Shouldn't [this line](https://github.com/acdh-oeaw/apis-rdf-devops/blob/main/Dockerfile#L47) as well as the [reference to the variable](https://github.com/acdh-oeaw/apis-rdf-devops/blob/main/Dockerfile#L31) be removed since we're now using the CI/CD (or env) variable `$POETRY_ADDITIONAL_GROUPS` in `start.sh`, which could equally be used to install the dev dependencies? Not sure if this is an accidental leftover or if there's a good reason for keeping this check around.

Related: #16.

cc @sennierer @b1rger

**Comment by b1rger** [comment]
I think it makes sense to install as many dependencies as possible when the container is built and not every time the container is started.

**Comment by sennierer** [comment]
Yes, given that we (or at least I) use that Dockerfile also for local dev it is nice to have an option that allows for installing dev deps directly when the image is built, rather than every time when the container is restarted.

Given that this is optional anyway I would suggest to leave it like that for the moment.

Closing.

**Comment by koeaw** [comment]
So isn't this a variable that is _only_ used when developing locally?

I get that it makes more sense to included dependencies already when building, but a) why would we want to create a build with dev dependencies that's deployed for all projects (the assumption being the intention is to install dev dependencies for one particular project only) and b) where do we use this variable for CI/CD?
