### ISSUE TITLE
Django project documentation tooling + workflow

### ISSUE THREAD

**Issue by koeaw** [acdh-oeaw/apis-rdf-devops#49]
APIS-RDF doesn't currently have proper project documentation or a workflow for generating/updating docs.

Vanilla APIS docs used [Sphinx](https://www.sphinx-doc.org/en/master/), so it would make sense to stick to Sphinx for now also for APIS-RDF. Docs-related dependencies are best put in a separate dependency group for Poetry (separate from dev tools, and not part of default requirements).

We'll want to keep the docs for the submodules separate from the superproject, though the workflow for that will need more discussion. -> Can docs for all repos be generated from the superproject and still be self-contained? Does it make sense to update the docs that way (likelihood of commits not getting pushed to all remotes)? Can submodule docs still be updated independently of the superproject? Effect on dependency management? etc.

**apis-rdf-devops** doesn't come with docs at this point, so those would need to be created from scratch. **apis-core-rdf** already contains [a docs directory](https://github.com/acdh-oeaw/apis-core-rdf/tree/dev/docs) (presumably outdated, possibly a copy of old vanilla docs), which need updating.

**Comment by b1rger** [comment]
documentation in https://github.com/acdh-oeaw/apis-core-rdf is generated automatically using a github action, there is a poetry `docs` group that specifies sphinx as dependency and there is a `Makefile` in the docs directory and the step to run the build is also documented [in the sphinx documentation](https://www.sphinx-doc.org/en/master/usage/quickstart.html#running-the-build). I think this solves all the points raised in this issue - hence I'm closing the issue. If there is still something to be done regarding documentation, please reopen or create an issue in the suitable repository
