### ISSUE TITLE
IDE-specific files need documentation

### ISSUE THREAD

**Issue by koeaw** [acdh-oeaw/apis-rdf-devops#52]
The [.pycharm folder](https://github.com/acdh-oeaw/apis-rdf-devops/tree/main/.pycharm) should have a README added to it to explain what the contained file does (+ make it easier to document future additions to the folder).

The same might be true for the VS-related files and folders in the repo, but I can't speak to those.

**Comment by b1rger** [comment]
This repository is being phased out, so I'm closing this
