### ISSUE TITLE
Move `webpage` to separate repo or to apis-core

### ISSUE THREAD

**Issue by b1rger** [acdh-oeaw/apis-rdf-devops#59]

**Comment by koeaw** [comment]
Some of the templates in `webpage` are effectively copies of files used in `browsing`.

With the move to [a separate module for browsing](https://github.com/acdh-oeaw/apis-core-rdf/pull/111), `webpage` potentially being moved to a separate repo as well and copies of `browsing` [templates](https://github.com/acdh-oeaw/apis-core-rdf/tree/dev/apis_core/apis_metainfo/templates/browsing) and [templatetags](https://github.com/acdh-oeaw/apis-core-rdf/tree/dev/apis_core/apis_metainfo/templatetags) also remaining in `apis_metainfo`, I don't know where changes to template files should go.

Is `webpage` meant to (continue to) duplicate `browsing`'s effort? Could `browsing` (largely) replace `webpage`?

Relatedly: could we find better names for the template tags? `webpage_extras` and `browsing_extras` suggest connections to the apps of the same name which don't exist (and which becomes even more confusing when e.g. functions in `browsing_extras.py` reference `webpage` templates). I'm not actually sure why there are two tags (historic reasons?) but could they be combined into one? There's also [an old draft PR](https://github.com/acdh-oeaw/apis-ontologies/pull/11) which meant to move the files away and into the directory for the example project (which doesn't affect or solve the naming issue, just mentioning it for completeness' sake).

**Comment by b1rger** [comment]
> Is `webpage` meant to (continue to) duplicate `browsing`'s effort? Could `browsing` (largely) replace `webpage`?

What *is* `browsing`'s effort? The [merged PR](https://github.com/acdh-oeaw/apis-core-rdf/pull/111) you linked to says: "In a JFX discussion it wasn't really clear what the module does" - thats why it was dropped. 


> Relatedly: could we find better names for the template tags? `webpage_extras` and `browsing_extras` suggest connections to the apps of the same name which don't exist (and which becomes even more confusing when e.g. functions in `browsing_extras.py` reference `webpage` templates). I'm not actually sure why there are two tags (historic reasons?) but could they be combined into one? There's also [an old draft PR](https://github.com/acdh-oeaw/apis-ontologies/pull/11) (now updated to newest `main`) which meant to move the files away and into the directory for the example project (which doesn't affect or solve the naming issue, just mentioning it for completeness' sake).

Please create separate issues for separate issues. If they are only mentioned somewhere in a comment, they will get lost. I'm not sure which tag modules you refer to. I don't know what that problem that mentioned PR tries to solve.

**Comment by b1rger** [comment]
Done in c6f9b393f0b9c7ad3f026aedb834f9a4e658cbc4
