### ISSUE TITLE
dal_select2 hack in manage.py

### ISSUE THREAD

**Issue by richardhadden** [acdh-oeaw/apis-rdf-devops#61]
We would like to remove the `dal_select2` hack in `manage.py`, so that a vanilla Django project can be created which does not rely on this hack.

**Context**
`dal_select2` has a bug in js code (`/static/autocomplete-light/select2.js`) where the `value` of a selection is used in place of the `id`. We introduced a hack (`manage.py#30`) to overwrite the problematic code in the js file.

**Current situation**
Newer versions of `django-autocomplete-light` have not corrected this issue. (It does not even seem that this is regarded as a bug, but is expected behaviour: https://github.com/yourlabs/django-autocomplete-light/issues/902)

As such, we need to keep some fix of this sort somewhere. Any suggestions for best place to move it (ideally in APIS-core, as it's actually a dependency of APIS-core) and some mechanism for running the fix? 

- Custom management command, called by Dockerfile after: `RUN bash -c "if [ $INSTALL_DEV == 'true' ] ; then poetry install --no-root ; else poetry install --no-root --no-dev ; fi"` ?

**Comment by b1rger** [comment]
> It does not even seem that this is regarded as a bug, but is expected behaviour: [yourlabs/django-autocomplete-light#902](https://github.com/yourlabs/django-autocomplete-light/issues/902)

actually, upstream asked two times for a reproducible example of the bug, so they could fix it. maybe we can provide that.

besides that: maybe we can ship our own `select2.js` and `select2.min.js` until this is fixed- i think that would be a cleaner solution than modifying the file on every startup

**Comment by koeaw** [comment]
Link to the referenced fix in `manage.py` to save the next person a click: https://github.com/acdh-oeaw/apis-rdf-devops/blob/main/manage.py#L30

**Comment by b1rger** [comment]
actually, this is only a problem because we set the `data-tags` setting in https://github.com/acdh-oeaw/apis-core-rdf/blob/e31351d597e90a9d3ca3a0400b06df758f766bb5/apis_core/apis_relations/forms2.py#L71 - this allows to create new options on the fly. But IMO this does not make any sense, because we have no logic to create new relations/properties from the autocomplete forms, right?

**Comment by b1rger** [comment]
for now replaced by https://github.com/acdh-oeaw/apis-override-select2js
