### ISSUE TITLE
Inclusion of django-charts results in warning

### ISSUE THREAD

**Issue by koeaw** [acdh-oeaw/apis-rdf-devops#64]
**Describe the bug**
Running the app currently produces the following warning:

```
charts.ChartConfig: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
	HINT: Configure the DEFAULT_AUTO_FIELD setting or the ChartsConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
charts.ChartType: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
	HINT: Configure the DEFAULT_AUTO_FIELD setting or the ChartsConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
```

I'm assuming this was caused by the inclusion of [acdh-django-charts](https://github.com/acdh-oeaw/acdh-django-charts) in `apis-core-rdf` here: https://github.com/acdh-oeaw/apis-core-rdf/commit/014da3eb1728734f50565fefc5cf998e09767ae1.

The Django release notes for 3.2 [present two ways to solve this](https://docs.djangoproject.com/en/3.2/releases/3.2/#customizing-type-of-auto-created-primary-keys) – I ended up adding

```python
DEFAULT_AUTO_FIELD = "django.db.models.AutoField"
```
to our ontologies project's settings as a short-term solution but think this should be fixed on the charts project's end for better (re)usability.

Still, leaving this here for now to document the problem & a possible solution for users of our project.

**Comment by b1rger** [comment]
> I'm assuming this was caused by the inclusion of [acdh-django-charts](https://github.com/acdh-oeaw/acdh-django-charts) in `apis-core-rdf` here: [acdh-oeaw/apis-core-rdf@014da3e](https://github.com/acdh-oeaw/apis-core-rdf/commit/014da3eb1728734f50565fefc5cf998e09767ae1).

(just FTR: no, acdh-django-charts was already a dependency of `apis-rdf-devops` since the initial commit, the commit in `apis-core-rdf` just moved the dependency there, because thats where it should be)

**Comment by koeaw** [comment]
Thx for the added context. So maybe it was actually the upgrade of our Django version that made the warning appear.
