### ISSUE TITLE
create `prosnet-workflows` repository

### ISSUE THREAD

**Issue by sennierer** [acdh-oeaw/apis-rdf-devops#83]
should contain:
- reuseable GitHub actions for deploying APIS instances
- reuseable GitHub actions for linting and formatting

**Comment by b1rger** [comment]
repository is created, workflows will be integrated one by one, see
https://github.com/acdh-oeaw/prosnet-workflows/issues/3
https://github.com/acdh-oeaw/prosnet-workflows/issues/2
