### ISSUE TITLE
Pin `apis-webpage`

### ISSUE THREAD

**Issue by b1rger** [acdh-oeaw/apis-rdf-devops#91]
`apis-webpage`  introduced versions and new commits are now regularly added on top of `main`. But the `pyproject.toml` of `apis-rdf-devops` is still pointing to `main`. If projects choose to keep using this repository, it might be a good idea to pin `apis-webpage` to a commit instead of a branch

CC: @acdh-oeaw/prosnet

**Comment by sennierer** [comment]
pin it to the version tags v0.1 for the moment -> move to dedicated devops repos per project to get rid of the versions issues

**Comment by sennierer** [comment]
closing as not used anymore
